"""Fix foreign key for lecturer_id

Revision ID: 3f00c2b16931
Revises: 
Create Date: 2025-05-09 11:08:37.602537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f00c2b16931'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('schedules')
    op.drop_table('exams')
    op.drop_table('courses')
    op.drop_index('ix_Users_user_id', table_name='Users')
    op.drop_table('Users')
    op.drop_table('system_logs')
    op.drop_table('student_responses')
    op.drop_table('programs')
    op.alter_column('lecturers', 'lecturer_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('lecturers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lecturers', 'active_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('lecturers', 'del_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_lecturers_staff_id'), 'lecturers', ['staff_id'], unique=False)
    op.create_unique_constraint(None, 'lecturers', ['lecturer_id'])
    op.create_unique_constraint(None, 'lecturers', ['email'])
    op.create_unique_constraint(None, 'lecturers', ['phone_number'])
    op.alter_column('students', 'student_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('students', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'active_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('students', 'del_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_unique_constraint(None, 'students', ['student_id'])
    op.create_unique_constraint(None, 'students', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.alter_column('students', 'del_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('students', 'active_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('students', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'student_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'lecturers', type_='unique')
    op.drop_constraint(None, 'lecturers', type_='unique')
    op.drop_constraint(None, 'lecturers', type_='unique')
    op.drop_index(op.f('ix_lecturers_staff_id'), table_name='lecturers')
    op.alter_column('lecturers', 'del_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lecturers', 'active_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lecturers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lecturers', 'lecturer_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('programs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('programs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('program_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='programs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('student_responses',
    sa.Column('response_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name='student_responses_question_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name='student_responses_student_id_fkey'),
    sa.PrimaryKeyConstraint('response_id', name='student_responses_pkey')
    )
    op.create_table('system_logs',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('activity_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='system_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('log_id', name='system_logs_pkey')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='Users_pkey'),
    sa.UniqueConstraint('email', name='Users_email_key')
    )
    op.create_index('ix_Users_user_id', 'Users', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('course_id', sa.INTEGER(), server_default=sa.text("nextval('courses_course_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('lecturer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.staff_id'], name='fk_courses_lecturer'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.user_id'], name='courses_lecturer_id_fkey'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name='courses_program_id_fkey'),
    sa.PrimaryKeyConstraint('course_id', name='courses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.INTEGER(), server_default=sa.text("nextval('exams_exam_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exam_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('exam_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exam_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name='exams_course_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='exams_created_by_fkey'),
    sa.PrimaryKeyConstraint('exam_id', name='exams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name='schedules_course_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='schedules_created_by_fkey'),
    sa.PrimaryKeyConstraint('schedule_id', name='schedules_pkey')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expected_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], name='questions_exam_id_fkey'),
    sa.PrimaryKeyConstraint('question_id', name='questions_pkey')
    )
    # ### end Alembic commands ###
